spring.application.name=myfirstapp
coach.name = david anthony
bus.name = first bus
management.endpoints.web.exposure.include=*
#management.endpoints.web.exposure.exclude=health,info
management.info.env.enabled=true

info.app.name = first app
info.app.description = This is the basic info on first app
info.app.version = 1.0.0.1